flags=-g -Wall -Wextra -Werror -pedantic

ll:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/test.m

#Push alone
006:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/00-pushAlone.m

#null file
005:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/00-nullFile.m
#no line
004:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/00-noLine.m

#negative numbers
003:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/00-negativeDigit.m

#no function
002:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/00-noFunction.m

001:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/000.m
00:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/00.m
#is digit
0:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/00-isdigit.m


#pint
1:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/06.m
#pop
2:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/07.m
#swap
3:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/09.m

# add
4:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/12.m
#nop
5:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/p5-nop.m

#sub
6:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/19.m
#div
7:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/p7-div.m
	./test ../bytecodes/p7-divZero.m


#mul
8:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/p8-mul.m
#module
9:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/p9-mod.m
#comments
10:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/p10-comments.m
#pchar
11:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/28.m
#pstr
12:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/31.m

01:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/06.m



